/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Stitch Design System - Academic Precision
        primary: "#003441",
        "primary-container": "#0f4c5c",
        "on-primary": "#ffffff",
        "on-primary-container": "#87bbce",
        secondary: "#006c49",
        "secondary-container": "#6cf8bb",
        "on-secondary": "#ffffff",
        tertiary: "#482700",
        "tertiary-container": "#623d13",
        "on-tertiary": "#ffffff",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        surface: "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#40484b",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#70787c",
        "outline-variant": "#c0c8cb",
        "surface-tint": "#306576",
        "primary-fixed": "#b6ebfe",
        "primary-fixed-dim": "#9acee1",
        "on-primary-fixed": "#001f28",
        "on-primary-fixed-variant": "#114d5d",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-fixed": "#ffdcbe",
        "tertiary-fixed-dim": "#f3bc87",
        "on-tertiary-fixed": "#2c1600",
        "on-tertiary-fixed-variant": "#643e14",
        "inverse-primary": "#9acee1",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        margin: "32px",
        gutter: "24px",
        sm: "16px",
        xs: "8px",
        lg: "32px",
        base: "4px",
        md: "24px",
        xl: "48px",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-sm": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "display-lg": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      // Custom Stitch spacing utilities
      padding: {
        margin: "32px",
        gutter: "24px",
      },
      gap: {
        gutter: "24px",
      },
    },
  },
  plugins: [],
};
