const { Activity } = require('../models');
const { seedRows } = require('./helpers');

const activities = [
  { name: 'Taller de Robótica', description: 'Taller de robótica educativa' },
  { name: 'Seminario de Linux', description: 'Seminario introductorio a Linux' },
  { name: 'Jornadas de Computación', description: 'Jornadas anuales de computación' },
  { name: 'Curso de Python Avanzado', description: 'Curso avanzado de Python' },
  { name: 'Hackathon Universitario', description: 'Participación en hackathon' },
  { name: 'Taller de Empleabilidad', description: 'Taller de preparación laboral' },
  { name: 'Pasantía de Investigación I', description: 'Pasantía en investigación' },
  { name: 'Configuración de Servidores', description: 'Curso de administración de servidores' },
  { name: 'Seminario de IA', description: 'Seminario de inteligencia artificial' },
  { name: 'Voluntariado de Reforestación', description: 'Voluntariado de reforestación urbana' },
  { name: 'Taller de Reciclaje', description: 'Taller de reciclaje y gestión de residuos' },
  { name: 'Curso de Energías Limpias', description: 'Curso sobre energías renovables' },
  { name: 'Seminario de Cambio Climático', description: 'Seminario sobre cambio climático global' },
  { name: 'Conferencia de Biodiversidad', description: 'Conferencia anual de biodiversidad' },
  // TUP 2025 - Créditos por Espacio de Integración Curricular
  { name: 'Desarrollo de Aplicaciones, en UNAHUR (CR012_033)', description: 'Crédito EIC' },
  { name: 'Desarrollo de Práctica Profesional Supervisada (PPS) (CR011_033)', description: 'Crédito EIC' },
  { name: 'Proyecto Integrador (CR030_033)', description: 'Crédito EIC' },
  { name: 'ACA: Jornadas de la Industria 1ra Participación - Día 1 (CR_ITI_12)', description: 'Crédito EIC' },
  { name: 'ACA: Jornadas de la Industria 1ra Participación - Día 2 (CR_ITI_13)', description: 'Crédito EIC' },
  { name: 'Exposición en Jornadas - 1ra Participación (CR_ITI_14)', description: 'Crédito EIC' },
  // TUP 2025 - Créditos por actividades formativas académicas y profesionales
  { name: 'Participación como asistente en Jornadas / Workshops / Congresos (CR002)', description: 'Crédito formativo académico/profesional' },
  { name: 'Talleres Especiales (más de 32hs) (CR004)', description: 'Crédito formativo académico/profesional' },
  { name: 'Talleres especiales - Taller de Github (CR003)', description: 'Crédito formativo académico/profesional' },
  { name: 'Participación en Competencias Estudiantiles - Rally Innovación 2023 (CR015)', description: 'Crédito formativo académico/profesional' },
  { name: 'Talleres Especiales - Gestión de Firewall (CR014)', description: 'Crédito formativo académico/profesional' },
  { name: 'Talleres especiales - Taller de Gestión de la seguridad informática (CR013)', description: 'Crédito formativo académico/profesional' },
  { name: 'Participación como asistente en Jornadas / Workshops / Congresos - (Evento de 1 día presencial) (CR017)', description: 'Crédito formativo académico/profesional' },
  { name: 'Talleres Especiales - Curso de Iniciación al Mundo Laboral (CR018)', description: 'Crédito formativo académico/profesional' },
  { name: 'Participación en Proyectos Abiertos (CR021)', description: 'Crédito formativo académico/profesional' },
  { name: 'Intercambios estudiantiles presenciales y/o virtuales (CR023)', description: 'Crédito formativo académico/profesional' },
  { name: 'Formación Profesional (CR024)', description: 'Crédito formativo académico/profesional' },
  { name: 'Cursadas Voluntarias en otras Universidades (CR026)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller de Procesamiento digital de imágenes (CR027)', description: 'Crédito formativo académico/profesional' },
  { name: 'Participación en competencias estudiantiles (CR029)', description: 'Crédito formativo académico/profesional' },
  { name: 'Formación Profesional (Segunda Participación) (CR024b)', description: 'Crédito formativo académico/profesional' },
  { name: 'Rally Latinoamericano de Innovación - 1ra participación (CR_ITI_001)', description: 'Crédito formativo académico/profesional' },
  { name: 'Rally Latinoamericano de Innovación - 2da participación (CR_ITI_001b)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Enlaces Inalámbricos Fijos (CR036)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Introducción al Cómputo Paralelo (CR038)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Oracle SQL & PL SQL (CR034)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Project Management (CR033)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Redes Móviles Celulares (CR035)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Redes de Fibra Óptica (CR037)', description: 'Crédito formativo académico/profesional' },
  { name: 'Curso Introducción a UML (CR039)', description: 'Crédito formativo académico/profesional' },
  { name: 'Charlas con Graduados (al menos 4 charlas) (CR046)', description: 'Crédito formativo académico/profesional' },
  { name: 'Creación y Animación de Personajes 2D-Del boceto al Sprite Sheet (CR042)', description: 'Crédito formativo académico/profesional' },
  { name: 'Cómo hacer videojuegos sin volverse loco: Gestión, Diseño y Validación de Usuario (CR041)', description: 'Crédito formativo académico/profesional' },
  { name: 'De wollok a Java (CR055)', description: 'Crédito formativo académico/profesional' },
  { name: 'Del Prototipo al Portfolio Profesional (CR044)', description: 'Crédito formativo académico/profesional' },
  { name: 'Diseño Narrativo de Personajes: Cómo comenzar un relato (CR043)', description: 'Crédito formativo académico/profesional' },
  { name: 'Git (CR053)', description: 'Crédito formativo académico/profesional' },
  { name: 'GraphQL en Springboot (CR054)', description: 'Crédito formativo académico/profesional' },
  { name: 'Lenguajes educativos para aprender a programar (CR052)', description: 'Crédito formativo académico/profesional' },
  { name: 'PIA Taller 1 (CR047)', description: 'Crédito formativo académico/profesional' },
  { name: 'PIA Taller 2 (CR048)', description: 'Crédito formativo académico/profesional' },
  { name: 'PIA Taller 3 (CR049)', description: 'Crédito formativo académico/profesional' },
  { name: 'Presentación de nuevos planes de las carreras de informática (CR040)', description: 'Crédito formativo académico/profesional' },
  { name: 'Principios básicos de la Seguridad de la Información y la Ciberseguridad (CR057)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller Introductorio de Integrales (CR050)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller de Introducción al procesamiento digital de Imágenes (CR051)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller de programación (CR056)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller de robótica (CR045)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller de uso de herramientas para el procesamiento de datos (CR059)', description: 'Crédito formativo académico/profesional' },
  { name: 'Vibe Coding (CR058)', description: 'Crédito formativo académico/profesional' },
  { name: 'Construcción de un CV (CR061)', description: 'Crédito formativo académico/profesional' },
  { name: 'De la Idea al Código (CR062)', description: 'Crédito formativo académico/profesional' },
  { name: 'Taller de informática (CR060)', description: 'Crédito formativo académico/profesional' },
  // TUP 2025 - Créditos por actividades sociales, culturales y deportivas
  { name: 'Talleres culturales (CR007)', description: 'Crédito social/cultural/deportivo' },
  { name: 'Talleres deportivos (CR006)', description: 'Crédito social/cultural/deportivo' },
  { name: 'Voluntariados (CR005)', description: 'Crédito social/cultural/deportivo' },
  { name: 'UNAHUR@TIC #1 - Encuentro de Informática (CR019)', description: 'Crédito social/cultural/deportivo' },
  { name: 'UNAHUR@TIC #1 - Encuentro de Informática (medio día) (CR020)', description: 'Crédito social/cultural/deportivo' },
  { name: 'Taller de eSport (CR022)', description: 'Crédito social/cultural/deportivo' },
  { name: 'UNAHUR@TIC - Encuentro de Informática (segunda participación) (CR028)', description: 'Crédito social/cultural/deportivo' },
  { name: 'Actividades de Perspectiva de Género (12hs) (CR031)', description: 'Crédito social/cultural/deportivo' },
  { name: 'UNAHUR@TIC - Encuentro de Informática (tercera participación) (CR028b)', description: 'Crédito social/cultural/deportivo' },
  { name: 'Actividades de Biblioteca (CR032)', description: 'Crédito social/cultural/deportivo' },
  // TUP 2025 - Créditos por actividades formativas en docencia e investigación
  { name: 'Colaboración en materias (CR010)', description: 'Crédito de docencia/investigación' },
  { name: 'Participación como Estudiante Asistente (CR009)', description: 'Crédito de docencia/investigación' },
  { name: 'Participación en el programa Un estudiantes/Un compañero/a (CR008)', description: 'Crédito de docencia/investigación' },
  { name: 'Asistencia Técnica a grupos de Investigación de la Universidad (CR016_033)', description: 'Crédito de docencia/investigación' },
  { name: 'Participación en actividades de difusión académica (CR025)', description: 'Crédito de docencia/investigación' },
  { name: 'Participación en actividades de difusión académica (2da participación) (CR025b)', description: 'Crédito de docencia/investigación' },
  { name: 'Python Day (CR_ITI_002)', description: 'Crédito de docencia/investigación' },
  { name: 'Computación Cuántica (CR_ITI_010)', description: 'Crédito de docencia/investigación' },
  { name: 'Python Day (Segunda Participación) (CR_ITI_002b)', description: 'Crédito de docencia/investigación' },
];

async function seedActivities(transaction) {
  return seedRows(Activity, activities, ['name'], transaction);
}

module.exports = seedActivities;
