const { Subject } = require('../models');
const { seedRows } = require('./helpers');

const subjects = [
  { name: 'Matemática I', code: 'MAT-101', is_unahur: false, weekly_hours: 6 },
  { name: 'Programación I', code: 'PROG-101', is_unahur: false, weekly_hours: 6 },
  { name: 'Organización de Computadoras', code: 'ORG-101', is_unahur: false, weekly_hours: 4 },
  { name: 'Matemática II', code: 'MAT-102', is_unahur: false, weekly_hours: 6 },
  { name: 'Programación II', code: 'PROG-102', is_unahur: false, weekly_hours: 6 },
  { name: 'Algoritmos y Estructuras de Datos', code: 'AED-201', is_unahur: false, weekly_hours: 6 },
  { name: 'Bases de Datos', code: 'BD-201', is_unahur: false, weekly_hours: 6 },
  { name: 'Sistemas Operativos', code: 'SO-202', is_unahur: false, weekly_hours: 6 },
  { name: 'Ingeniería de Software', code: 'IS-301', is_unahur: false, weekly_hours: 6 },
  { name: 'Redes de Computadoras', code: 'RED-302', is_unahur: false, weekly_hours: 6 },
  { name: 'Proyecto Final Computación', code: 'PF-402', is_unahur: false, weekly_hours: 8 },
  { name: 'Inteligencia Artificial Aplicada', code: 'ECOM-01', is_unahur: false, weekly_hours: 4 },
  { name: 'Ciberseguridad', code: 'ECOM-02', is_unahur: false, weekly_hours: 4 },
  { name: 'Desarrollo Web Avanzado', code: 'ECOM-03', is_unahur: false, weekly_hours: 4 },
  { name: 'Computación en la Nube', code: 'ECOM-04', is_unahur: false, weekly_hours: 4 },
  { name: 'Sistemas Embebidos', code: 'ECOM-05', is_unahur: false, weekly_hours: 4 },
  { name: 'Química General', code: 'QUI-101', is_unahur: false, weekly_hours: 4 },
  { name: 'Biología General', code: 'BIO-101', is_unahur: false, weekly_hours: 4 },
  { name: 'Química Orgánica', code: 'QUI-102', is_unahur: false, weekly_hours: 4 },
  { name: 'Ecología General', code: 'ECO-201', is_unahur: false, weekly_hours: 4 },
  { name: 'Estadística', code: 'EST-201', is_unahur: false, weekly_hours: 4 },
  { name: 'Microbiología Ambiental', code: 'MIC-202', is_unahur: false, weekly_hours: 4 },
  { name: 'Operaciones Unitarias', code: 'OPE-301', is_unahur: false, weekly_hours: 6 },
  { name: 'Sistemas de Información Geográfica', code: 'SIG-302', is_unahur: false, weekly_hours: 4 },
  { name: 'Contaminación Ambiental', code: 'CON-401', is_unahur: false, weekly_hours: 4 },
  { name: 'Taller de Proyecto Final Ambiental', code: 'TPF-501', is_unahur: false, weekly_hours: 4 },
  { name: 'Proyecto Final Ambiental', code: 'PF-502', is_unahur: false, weekly_hours: 8 },
  { name: 'Evaluación de Impacto Ambiental', code: 'EAMB-01', is_unahur: false, weekly_hours: 4 },
  { name: 'Gestión de Residuos Urbanos', code: 'EAMB-02', is_unahur: false, weekly_hours: 4 },
  { name: 'Energías Renovables', code: 'EAMB-03', is_unahur: false, weekly_hours: 4 },
  { name: 'Tratamiento de Efluentes', code: 'EAMB-04', is_unahur: false, weekly_hours: 4 },
  { name: 'Ética Profesional', code: 'UNA-01', is_unahur: true, weekly_hours: 4 },
  { name: 'Nuevos Entornos Digitales', code: 'UNA-02', is_unahur: true, weekly_hours: 4 },
  { name: 'Problemática Ambiental Contemporánea', code: 'UNA-03', is_unahur: true, weekly_hours: 4 },
  { name: 'Taller de Comunicación Oral y Escrita', code: 'UNA-04', is_unahur: true, weekly_hours: 4 },
  // TUP 2025 - Obligatorias
  { name: 'Matemática para informática I', code: '788', is_unahur: false, weekly_hours: 6 },
  { name: 'Organización de computadoras I', code: '790', is_unahur: false, weekly_hours: 6 },
  { name: 'Introducción a lógica y problemas computacionales', code: '789', is_unahur: false, weekly_hours: 6 },
  { name: 'Nuevos entornos y lenguajes', code: '004', is_unahur: false, weekly_hours: 4 },
  { name: 'Taller de lenguajes de marcado y tecnologías web', code: '791', is_unahur: false, weekly_hours: 6 },
  { name: 'Programación estructurada', code: '792', is_unahur: false, weekly_hours: 6 },
  { name: 'Matemática para Informática II', code: '793', is_unahur: false, weekly_hours: 6 },
  { name: 'Inglés I', code: '030', is_unahur: false, weekly_hours: 4 },
  { name: 'Bases de datos', code: '754', is_unahur: false, weekly_hours: 6 },
  { name: 'Programación con objetos I', code: '753', is_unahur: false, weekly_hours: 6 },
  { name: 'Estructuras de datos', code: '752', is_unahur: false, weekly_hours: 6 },
  { name: 'Programación con Objetos II', code: '765', is_unahur: false, weekly_hours: 6 },
  { name: 'Inglés II', code: '043', is_unahur: false, weekly_hours: 4 },
  { name: 'Construcción de Interfaces de Usuario', code: '758', is_unahur: false, weekly_hours: 6 },
  { name: 'Estrategias de Persistencia', code: '759', is_unahur: false, weekly_hours: 6 },
  { name: 'Elementos de ingeniería de software', code: '760', is_unahur: false, weekly_hours: 6 },
  // TUP 2025 - Electivas
  { name: 'Elec_Programación funcional', code: '761', is_unahur: false, weekly_hours: 4 },
  { name: 'Elec_Programación Concurrente', code: '766', is_unahur: false, weekly_hours: 4 },
  { name: 'COMP_Seminarios', code: 'INF_COMP10', is_unahur: false, weekly_hours: 4 },
  { name: 'COMP_Sistemas de información geográfica', code: 'INF_COMP5', is_unahur: false, weekly_hours: 4 },
  { name: 'Elec_Redes de computadoras', code: '756', is_unahur: false, weekly_hours: 4 },
  { name: 'Elec_Organización de computadoras II', code: '795', is_unahur: false, weekly_hours: 4 },
  { name: 'Elec_Sistemas operativos', code: '757', is_unahur: false, weekly_hours: 4 },
  // TUP 2025 - UNAHUR completo del plan adjunto
  { name: 'AU_Abordaje de situaciones sociales complejas', code: 'AU_2', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Software libre y sociedad', code: 'AU_11', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Taller de escritura creativa', code: 'AU_12', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Análisis y diseño de políticas públicas', code: 'AU_3', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Ciencia Tecnología y sociedad', code: 'AU_4', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Culturas Juveniles', code: 'AU_5', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Filosofía', code: 'AU_6', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Pensamiento Nacional', code: 'AU_7', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Robótica', code: 'AU_8', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Universidad, territorio e intervenciones sociales', code: 'AU_9', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Literatura Argentina. Ficciones de la patria', code: 'AU_1', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Investigación cualitativa', code: 'AU_10', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Métodos participativos de transformación de conflictos', code: 'AU_13', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Malvinas: una Causa de nuestra América Latina', code: 'AU_14', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Pensar Hurlingham', code: 'AU_15', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Astro: Relación de la Humanidad con el Cosmos', code: 'AU_17', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Modos de ver el Mundo contemporáneo a través del lenguaje audiovisual', code: 'AU_16', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Ciudadania activa y compromiso social', code: 'AU_20', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Infancias, derechos y politicas', code: 'AU_18', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Innovacion y creatividad', code: 'AU_19', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Tecnicas de investigacion en opinion publica', code: 'AU_21', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Cuentos norteamericanos', code: 'AU_22', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Arte contemporáneo: un recorrido por la historia del siglo XX a través de las vanguardias artísticas', code: 'AU_30', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Educación Sexual Integral. Cuando lo esencial es visible a los ojos', code: 'AU_32', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Género y Sociedad: una nueva mirada para una era mas justa', code: 'AU_33', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Invitación a un clásico de la Literatura', code: 'AU_28', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Literatura y Memoria', code: 'AU_27', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Manipulacion genetica en humanos. Historia, mitos y realidades', code: 'AU_26', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Una Historia del Rock Nacional', code: 'AU_31', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Literatura y Política', code: 'AU_25', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Arte y Tecnología', code: 'AU_24', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_La vida secreta de las rocas', code: 'AU_23', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Introducción a la Imagen. (De la imagen fija a la imagen en movimiento)', code: 'AU_34', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Cuando los Pasados No Pasan: lugares de memoria', code: 'AU_35', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Pensamiento Ambiental Latinoamericano', code: 'AU_36', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Pensamiento Pedagógico Latinoamericano', code: 'AU_37', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_No sos vos, es Freud: una introducción al psicoanálisis', code: 'AU_39', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Introducción al Latín', code: 'AU_40', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Hacia una Práctica Profesional Inclusiva', code: 'AU_41', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Ciencias en la cocina', code: 'AU_42', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Cine documental: miradas desde el Sur', code: 'AU_43', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Repensar la discapacidad', code: 'AU_44', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Introducción al griego', code: 'AU_45', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Mal de tango. La historia argentina a través del tango', code: 'AU_46', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_ESI en el campo de la salud: un abordaje integral sobre la sexualidad', code: 'AU_47', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Debates políticos actuales. Ideas para pensar el mundo de hoy', code: 'AU_48', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Educación y memoria: la transmisión del pasado reciente en las aulas', code: 'AU_49', is_unahur: true, weekly_hours: 4 },
  { name: 'CINE.AR La Argentina contemporánea a través del cine', code: 'AU_50', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Derechos: los tuyos, los míos, los nuestros', code: 'AU_52', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Modos de ver el mundo contemporáneo a través del lenguaje audiovisual. Cine, jóvenes y trabajo', code: 'AU_51', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Ciencias del fin del mundo', code: 'AU_53', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Ciencia, tecnología e innovación para el desarrollo', code: 'AU_54', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Habilidades blandas: un acercamiento al mundo del trabajo', code: 'AU_55', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_Soberanía alimentaria para la inclusión social', code: 'AU_56', is_unahur: true, weekly_hours: 4 },
  { name: 'AU_El Holocausto, el abismo de la humanidad', code: 'AU_61', is_unahur: true, weekly_hours: 4 },
];

async function seedSubjects(transaction) {
  return seedRows(Subject, subjects, ['name'], transaction);
}

module.exports = seedSubjects;
